### ISSUE TITLE
Add `nanquantile` array function

### ISSUE THREAD

**Issue by maawoo** [numbagg/numbagg#161]
Unfortunately numpy's `nanquantile` method has been rather slow since quite some time (see https://github.com/numpy/numpy/issues/16575) resulting in performance issues upstream (e.g., xarray: https://github.com/pydata/xarray/issues/7377).

I didn't find any hints on a planned implementation. Do you think this could be done at least for the default `linear` method?

**Comment by max-sixty** [comment]
Yes, I'd be happy to have a go at this.

Do we have an idea of why there's such a difference between the `percentile` and `nanpercentile` performance? 

A naive version of this would be:
- Sort the array
- Count the NaNs
- Calculate the position(s) given the percentile(s) and count of NaNs
- Interpolate where necessary

But maybe there are better ways?

**Comment by dcherian** [comment]
Surfacing this blogpost with tricks here: https://krstn.eu/np.nanpercentile()-there-has-to-be-a-faster-way/

**Comment by max-sixty** [comment]
We could start with a version of that in numba — won't be _that_ much faster — the only loop we're taking out of the python interpreter is the loop over the percentiles (i.e. small n).

@kr-stn — if you see this — how would you feel about us using your code in numbagg? We have a BSD 3-clause license.

**Comment by bzah** [comment]
@max-sixty From what I can remember when adding interpolation methods for numpy's percentile, the main reason why nanpercentile is so slow is because the nanpercentile calls `apply_along_axis` and excludes NaNs before calling the base numpy's percentile method, see https://github.com/bzah/numpy/blob/f7911c67176c1d370be27726e87195699e4b581e/numpy/lib/nanfunctions.py#L1543C20-L1543C20
The blog post seems to say the same thing (and now I'm a bit sad that I didn't found this blog post before implementing xclim's version).

xclim's version deals with the ndarray directly, making things faster see https://github.com/Ouranosinc/xclim/blob/master/xclim/core/utils.py#L416

**Comment by max-sixty** [comment]
FYI this is proposed in bottleneck at https://github.com/pydata/bottleneck/issues/433 too, no implementation yet

**Comment by max-sixty** [comment]
Merged in #166
